---
openapi: 3.0.1
info:
  title: Deloitte Api
  version: '1.0'
paths:
  "/opal-batch-cubic-ingestion/v1/ctp/trigger-ingestion":
    post:
      tags:
      - deloitte
      parameters:
      - name: deloitte
